FPS.MVC/Models/ErrorViewModel.cs
namespace FPS.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FPS.MVC/Controllers/AuthenticationController.cs
using FPS.BusinessLayer.ViewModel.Authentication;
using FPS.BusinessLayer.ViewModel.AuthenticationModel;
using FPS.MVC.Models;
using FPS.MVC.Services.Authenticate;
using FPS.MVC.Services.Company;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using NuGet.Protocol;
using System.Diagnostics;

namespace FPS.MVC.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly IAuthenticationService _authenService;

        private readonly IHttpContextAccessor _httpContextAccessor;

        public AuthenticationController(IAuthenticationService authenService, IHttpContextAccessor httpContextAccessor)
        {
            _authenService = authenService;
            _httpContextAccessor = httpContextAccessor;
        }

        public async Task<IActionResult> Index(SignInModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _authenService.SignInAsync(model);
                var token = result.AccessToken;

                if (token != null)
                {
                    if (!string.IsNullOrEmpty(token.ToString()))
                    {
                        HttpContext.Session.SetString("AccessToken", token.ToString());
                        return RedirectToAction("Index", "Home");
                    }
                }
            }

            // ModelState không hợp lệ hoặc đăng nhập không thành công, hiển thị lại form với thông báo lỗi
            ModelState.AddModelError("", "Login failed. Please try again.");
            return View(model);
        }

        public async Task<IActionResult> SignUp(SignUpModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _authenService.SignUpAsync(model);
                if (result != null)
                {
                    return RedirectToAction("Index", "Authentication");
                }
            }

            // ModelState không hợp lệ hoặc đăng nhập không thành công, hiển thị lại form với thông báo lỗi
            ModelState.AddModelError("", "Signup Failed. Please try again.");
            return View(model);
        }

        public IActionResult Logout()
        {
            _httpContextAccessor.HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FPS.MVC/Controllers/CompanyController.cs
using FPS.MVC.ApiConfig;
using FPS.MVC.Models;
using FPS.MVC.Services.Company;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Net.Http.Headers;

namespace FPS.MVC.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyService _companyService;

        public CompanyController(ICompanyService companyService)
        {
            _companyService = companyService;
        }

        public async Task<IActionResult> Index()
        {
            var token = HttpContext.Session.GetString("AccessToken");

            if (string.IsNullOrEmpty(token))
            {
                return RedirectToAction("Index", "Home");
            }

            var data = await _companyService.GetAllCompany(token);
            return View(data);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FPS.MVC/Controllers/HomeController.cs
using FPS.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace FPS.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var token = HttpContext.Session.GetString("AccessToken");

            if (token != null)
            {
                var tokenHandler = new JwtSecurityTokenHandler();
                var jwtToken = tokenHandler.ReadJwtToken(token);

                var email = jwtToken.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
                ViewData["UserEmail"] = email;
            }

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FPS.MVC/Views/Authentication/Index.cshtml
@model FPS.BusinessLayer.ViewModel.AuthenticationModel.SignInModel

@{
    ViewData["Title"] = "Login";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/authen.css">
    <title>Modern Login Page</title>
</head>

<body>
    <div class="wrapper" id="wrapper">
            @using (Html.BeginForm("Index", "Authentication", FormMethod.Post))
            {
                <h1>Login</h1>
                <div class="input-box">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @placeholder = "Email" })
                </div>
                <div class="input-box">
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                </div>
                <div class="remember-forgot">
                    <label><input type="checkbox">Remember me</label>
                    <a href="#">Forgot Password?</a>
                </div>
                <button class="btn" type="submit">Login</button>
                <div class="register-link">
                    <a href="@Url.Action("SignUp", "Authentication")">Don't have an account? Sign Up</a>
                </div>
            }
    </div>
    <script src="~/js/authen.js"></script>
</body>

</html>

FPS.MVC/Views/Authentication/SignUp.cshtml
@model FPS.BusinessLayer.ViewModel.Authentication.SignUpModel

@{
    ViewData["Title"] = "SignUp";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="~/css/authen.css">
    <title>SignUp Page</title>
</head>

<body>
    <div class="container" id="container">
        <div class="wrapper sign-in">
            @using (Html.BeginForm("SignUp", "Authentication", FormMethod.Post))
            {
                <h1>Sign Up</h1>
                <div class="input-box">
                    @Html.TextBoxFor(m => m.FullName, new { @class = "form-control", @placeholder = "Full Name" })
                </div>
                <div class="input-box">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @placeholder = "Email" })
                </div>
                <div class="input-box">
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                </div>
                <div class="input-box">
                    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control", @placeholder = "Confirm Password" })
                </div>
                <button class="btn" type="submit">Sign Up</button>
                <div class="register-link">
                <a href="@Url.Action("Index", "Authentication")">You already have an account? Sign In</a>
                </div>
            }
        </div>
    </div>

    <script src="~/js/authen.js"></script>
</body>

</html>

FPS.MVC/Views/Company/Index.cshtml
@model List<FPS.BusinessLayer.ViewModel.Company.CompanyModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Company Khoa</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Company Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

FPS.MVC/Views/Home/Index.cshtml
@{
    var userEmail = ViewData["UserEmail"] as string;
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ul class="insights">
    <li>
        <i class='bx bx-calendar-check'></i>
        <span class="info">
            <h3>
                1,074
            </h3>
            <p>Paid Order</p>
        </span>
    </li>
    <li>
        <i class='bx bx-show-alt'></i>
        <span class="info">
            <h3>
                3,944
            </h3>
            <p>Site Visit</p>
        </span>
    </li>
    <li>
        <i class='bx bx-line-chart'></i>
        <span class="info">
            <h3>
                14,721
            </h3>
            <p>Searches</p>
        </span>
    </li>
    <li>
        <i class='bx bx-dollar-circle'></i>
        <span class="info">
            <h3>
                $6,742
            </h3>
            <p>Total Sales</p>
        </span>
    </li>
</ul>
<!-- End of Insights -->

<div class="bottom-data">
    <div class="orders">
        <div class="header">
            <i class='bx bx-receipt'></i>
            <h3>Recent Orders</h3>
            <i class='bx bx-filter'></i>
            <i class='bx bx-search'></i>
        </div>
        <table>
            <thead>
                <tr>
                    <th>User</th>
                    <th>Order Date</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <img src="images/profile-1.jpg">
                        <p>John Doe</p>
                    </td>
                    <td>14-08-2023</td>
                    <td><span class="status completed">Completed</span></td>
                </tr>
                <tr>
                    <td>
                        <img src="images/profile-1.jpg">
                        <p>John Doe</p>
                    </td>
                    <td>14-08-2023</td>
                    <td><span class="status pending">Pending</span></td>
                </tr>
                <tr>
                    <td>
                        <img src="images/profile-1.jpg">
                        <p>John Doe</p>
                    </td>
                    <td>14-08-2023</td>
                    <td><span class="status process">Processing</span></td>
                </tr>
            </tbody>
        </table>
    </div>

    <!-- Reminders -->
    <div class="reminders">
        <div class="header">
            <i class='bx bx-note'></i>
            <h3>Remiders</h3>
            <i class='bx bx-filter'></i>
            <i class='bx bx-plus'></i>
        </div>
        <ul class="task-list">
            <li class="completed">
                <div class="task-title">
                    <i class='bx bx-check-circle'></i>
                    <p>Start Our Meeting</p>
                </div>
                <i class='bx bx-dots-vertical-rounded'></i>
            </li>
            <li class="completed">
                <div class="task-title">
                    <i class='bx bx-check-circle'></i>
                    <p>Analyse Our Site</p>
                </div>
                <i class='bx bx-dots-vertical-rounded'></i>
            </li>
            <li class="not-completed">
                <div class="task-title">
                    <i class='bx bx-x-circle'></i>
                    <p>Play Footbal</p>
                </div>
                <i class='bx bx-dots-vertical-rounded'></i>
            </li>
        </ul>
    </div>
    <!-- End of Reminders-->

FPS.MVC/Views/Shared/_Layout.cshtml
@{
    var userEmail = ViewData["UserEmail"] as string;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/sb-admin/css/style.css" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <title>FPS HomePage</title>
    <style>
        .buttonLogin {
            appearance: none;
            background-color: transparent;
            border: 2px solid #1A1A1A;
            border-radius: 15px;
            box-sizing: border-box;
            color: #3B3B3B;
            cursor: pointer;
            display: inline-block;
            font-family: Roobert,-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";
            font-size: 16px;
            font-weight: 600;
            line-height: normal;
            margin: 0;
            min-height: 20px;
            min-width: 0;
            outline: none;
            padding: 5px 12px;
            text-align: center;
            text-decoration: none;
            transition: all 300ms cubic-bezier(.23, 1, 0.32, 1);
            user-select: none;
            -webkit-user-select: none;
            touch-action: manipulation;
            width: 8%;
            will-change: transform;
        }

            .buttonLogin:disabled {
                pointer-events: none;
            }

            .buttonLogin:hover {
                color: #fff;
                background-color: #1A1A1A;
                box-shadow: rgba(0, 0, 0, 0.25) 0 8px 15px;
                transform: translateY(-2px);
            }

            .buttonLogin:active {
                box-shadow: none;
                transform: translateY(0);
            }

        .profile {
            position: relative;
            display: inline-block;
        }

            .profile img {
                width: 40px;
                height: 40px;
                border-radius: 50%;
                cursor: pointer;
            }

        .dropdown-menu {
            display: none;
            position: absolute;
            z-index: 1;
            background-color: #fff;
            min-width: 200px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
            padding: 12px 0;
            border-radius: 8px;
            right: 0;
            overflow: hidden;
        }

            .dropdown-menu a,
            .dropdown-menu .btn {
                display: block;
                text-decoration: none;
                color: #333;
                padding: 10px 20px;
                transition: all 0.3s ease;
            }

                .dropdown-menu a:hover,
                .dropdown-menu .btn:hover {
                    background-color: #f5f5f5;
                    color: #666;
                }

        .btn {
            background: none;
            border: none;
            cursor: pointer;
            font-size: 16px;
            font-family: inherit;
            padding: 0;
            width: 100%;
            text-align: left;
        }

            .btn:hover {
                color: #666;
            }

        .dropdown-menu::before {
            content: '';
            position: absolute;
            top: -8px;
            right: 16px;
            width: 0;
            height: 0;
            border-left: 8px solid transparent;
            border-right: 8px solid transparent;
            border-bottom: 8px solid #fff;
        }
    </style>
</head>

<body>

    <!-- Sidebar -->
    <div class="sidebar">
        <a href="#" class="logo">
            <i class='bx bx-code-alt'></i>
            <div class="logo-name"><span>Nhu</span>Khoa</div>
        </a>

        <ul class="side-menu">
            <li><a href="#"><i class='bx bxs-dashboard'></i>Dashboard</a></li>
            <li><a asp-controller="Company" asp-action="Index"><i class='bx bxs-dashboard'></i>Company</a></li>
            <li><a href="#"><i class='bx bx-store-alt'></i>Shop</a></li>
            <li class="active"><a href="#"><i class='bx bx-analyse'></i>Analytics</a></li>
            <li><a href="#"><i class='bx bx-message-square-dots'></i>Tickets</a></li>
            <li><a href="#"><i class='bx bx-group'></i>Users</a></li>
            <li><a href="#"><i class='bx bx-cog'></i>Settings</a></li>
        </ul>
        <ul class="side-menu">
            <li>
                <a href="#" class="logout">
                    <i class='bx bx-log-out-circle'></i>
                    Logout
                </a>
            </li>
        </ul>
    </div>
    <!-- End of Sidebar -->
    <!-- Main Content -->
    <div class="content">
        <!-- Navbar -->
        <nav>
            <i class='bx bx-menu'></i>
            <form action="#">
                <div class="form-input">
                    <input type="search" placeholder="Search...">
                    <button class="search-btn" type="submit"><i class='bx bx-search'></i></button>
                </div>
            </form>
            <input type="checkbox" id="theme-toggle" hidden>
            <label for="theme-toggle" class="theme-toggle"></label>
            <a href="#" class="notif">
                <i class='bx bx-bell'></i>
                <span class="count">12</span>
            </a>

            @if (!string.IsNullOrEmpty(userEmail))
            {
                <div class="profile">
                    <img src="../img/defaultShinvatar.jpg" id="profileImage">
                    <div class="dropdown-menu">
                        <a href="#">Edit Profile</a>
                        <form id="logoutForm" asp-controller="Authentication" asp-action="Logout" method="post" class="form-inline">
                            @Html.AntiForgeryToken()
                            <button type="submit" class="btn">Logout</button>
                        </form>
                    </div>
                </div>
            }
            else
            {
                <button class="buttonLogin" role="button">Login</button>
            }
        </nav>

        <!-- End of Navbar -->

        <main>
            <div class="header">
                <div class="left">
                    <h1>Dashboard</h1>
                    <ul class="breadcrumb">
                        <li>
                            <a href="#">
                                Analytics
                            </a>
                        </li>
                        <li><a href="#" class="active">Shop</a></li>
                    </ul>
                </div>
                <a href="#" class="report">
                    <i class='bx bx-cloud-download'></i>
                    <span>Download CSV</span>
                </a>
            </div>
            <div>         
                @RenderBody()
            </div>
        </main>
    </div>
    <script src="~/sb-admin/js/index.js"></script>
    <script>
        //Button login
        document.addEventListener('DOMContentLoaded', function () {
            var buttonLogin = document.querySelector('.buttonLogin');
            buttonLogin.addEventListener('click', function () {
                var url = '@Url.Action("Index", "Authentication")';
                window.location.href = url;
            });
        });

        //Profile Image click
        document.addEventListener('DOMContentLoaded', function () {
            var profileImage = document.getElementById('profileImage');
            var dropdownMenu = document.querySelector('.dropdown-menu');

            profileImage.addEventListener('click', function () {
                dropdownMenu.style.display = dropdownMenu.style.display === 'none' ? 'block' : 'none';
            });

            window.addEventListener('click', function (event) {
                if (!event.target.matches('#profileImage')) {
                    dropdownMenu.style.display = 'none';
                }
            });
        });
    </script>
</body>
</html>